### ISSUE TITLE
Installation environment

### ISSUE THREAD

**Issue by wzy-Sarah** [xzenglab/MUFFIN#5]
It is difficult to run and install dgl successfully without a version provided. But I have tried out a feasible version.

- GPU: RTX2080Ti

- python: 3.6

- cuda: 10.2

- pytorch:   pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu102/torch_stable.html

- dgl:    pick the dgl from     https://pypi.tuna.tsinghua.edu.cn/simple/dgl-cu102/
`pip install dgl_cu102-0.4.3.post2-cp36-cp36m-manylinux1_x86_64.whl`

- maybe you will meet the problem:

OSError: libcublas.so.10: cannot open shared object file: No such file or directory

try this :  https://blog.csdn.net/cumina/article/details/121919529

**Comment by lisoio** [comment]
> 如果没有提供版本的话，dgl 很难成功运行和安装。不过我尝试了一个可行的版本。
> 
> * 显卡：RTX2080Ti
> * 蟒蛇：3.6
> * CUDA：10.2
> * pytorch： pip 安装 torch==1.10.1+cu102 torchvision==0.11.2+cu102 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu102/torch_stable.html
> * [dgl: 从https://pypi.tuna.tsinghua.edu.cn/simple/dgl-cu102/](https://pypi.tuna.tsinghua.edu.cn/simple/dgl-cu102/)中选择 dgl     [](https://pypi.tuna.tsinghua.edu.cn/simple/dgl-cu102/)
>   `pip install dgl_cu102-0.4.3.post2-cp36-cp36m-manylinux1_x86_64.whl`
> * 也许你会遇到这样的问题：
> 
> OSError：libcublas.so.10：无法打开共享对象文件：没有此文件或目录
> 
> 试试这个： https： [//blog.csdn.net/cumina/article/details/121919529](https://blog.csdn.net/cumina/article/details/121919529)

Dear, author, I hope to get your reply. I used the environment version you gave, but the error is still as follows:

root@autodl-container-6d25459816-16f8d803:~/autodl-tmp/MUFFIN_publish-main# python pretrain_smiles_embedding.py -fi data/DRKG/drugname_smiles.txt -m gin_supervised_masking -fo csv -sc smiles
Using backend: pytorch
Traceback (most recent call last):
  File "pretrain_smiles_embedding.py", line 13, in <module>
    from dgllife.model import load_pretrained
  File "/root/miniconda3/lib/python3.8/site-packages/dgllife/__init__.py", line 9, in <module>
    from . import model
  File "/root/miniconda3/lib/python3.8/site-packages/dgllife/model/__init__.py", line 6, in <module>
    from .gnn import *
  File "/root/miniconda3/lib/python3.8/site-packages/dgllife/model/gnn/__init__.py", line 10, in <module>
    from .gatv2 import *
  File "/root/miniconda3/lib/python3.8/site-packages/dgllife/model/gnn/gatv2.py", line 12, in <module>
    from dgl.nn.pytorch import GATv2Conv
ImportError: cannot import name 'GATv2Conv' from 'dgl.nn.pytorch' (/root/miniconda3/lib/python3.8/site-packages/dgl/nn/pytorch/__init__.py)
